name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The workflow runs on the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v2  # Check out the code from the repository

    - name: Install Node.js
      uses: actions/setup-node@v2  # Set up Node.js environment
      with:
        node-version: '16'  # Specify the Node.js version

    - run: npm install  # Install dependencies

    - run: npm run build:css  # Run the build script to generate the Tailwind CSS output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Deploy the site to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
        publish_dir: ./dist  # Specify the directory to publish (your built files)
